# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=500)),
                ('prescription', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=30)),
                ('doctor_dp', models.CharField(max_length=500)),
                ('contactno', models.CharField(max_length=10)),
                ('specialisation', models.CharField(max_length=40)),
                ('workplace', models.CharField(max_length=100)),
                ('password', models.CharField(default=None, max_length=300)),
            ],
        ),
    ]
