# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(default='', max_length=500)),
                ('patientcontact', models.CharField(default='', max_length=400)),
                ('symptoms', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmasists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmasistsname', models.CharField(max_length=500)),
                ('pharmasistscontact', models.IntegerField(max_length=10)),
                ('password', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medicine.Patient'),
        ),
    ]
