# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20170210_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='pharmacist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacistname', models.CharField(max_length=500)),
                ('dp', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Pharmasists',
        ),
        migrations.AddField(
            model_name='patient',
            name='dp',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='disease',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientcontact',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientname',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(default=0, max_length=5000),
        ),
    ]
